config/routes.rb
Rails.application.routes.draw do
  root 'stories#index'  
  devise_for :users
  resources :notes
  resources :stories
  resources :pirates, only: [:index, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord

  validates :user_id, numericality: true
  validates :story_id, numericality: true
	belongs_to :story
	belongs_to :user
	
end

app/models/story.rb
class Story < ApplicationRecord

  validates :title, presence: true, length: { in: 1..50 }
  validates :user_id, numericality: true
	has_many :notes, dependent: :destroy
	belongs_to :user
	
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  before_save :downcase_email

  # Include default devise modules. Others available are:
  # :confirmable, :recoverable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, 
         :validatable

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  # validates :username, presence: true, length: { in: 3..20 },
  #                     uniqueness: { case_sensitive: false }

  has_many :stories, dependent: :destroy
  has_many :notes, dependent: :destroy

  private

    def downcase_email
      email.downcase!
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username, :status])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:email, :username, :status])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.all
  end

  def show
  end

  def new
    @note = Note.new(note_params)
  end

  def edit
  end

  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to story_path(id: @note.story_id), notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    back_id = @note.story_id
    @note.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.json { head :no_content }
    end
  end

  private

    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:author, :note_entry, :story_id, :user_id)
    end
end

app/controllers/pirates_controller.rb
class PiratesController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  def index
    @stories = Story.all
  end

  def show
    @note = Note.new
  end

  def new
    @story = Story.new
    @note = Note.new
  end

  def edit
    @note = Note.new
  end

  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_story
      @story = Story.find(params[:id])
    end

    def story_params
      params.require(:story).permit(:title, :author, :body, :user_id, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pirates_helper.rb
module PiratesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/_navBar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
<!--     <div class="navbar-header"> -->
      <% if user_signed_in? %>
        <div class="navbar-header">
          <a class="navbar-brand" href="/">
            <%= current_user.username %>'s Bookshelf
          </a>
        </div>
          <ul class="nav navbar-nav">
            <li>
              <%= link_to 'New Story', new_story_path %>
            </li>
          </ul>
      <% else %>
        <div class="navbar-header">
          <%= link_to "Bookshelf", root_path, class: "navbar-brand" %>
        </div>
      <% end %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
<!--     </div> -->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.status %>
            <li><%= link_to "U-list", pirates_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"></span> <%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag asset_path('books-48-196164.png') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="bookshelf">
  	<div class="container-fluid">
      <%= render 'layouts/navBar' %>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
	    <%= yield %>
	  </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group">
    <%= form.text_area :note_entry, placeholder: "Something noteworthy...", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :story_id, value: @story.id %>
  </div>

  <div class="form-group">
    <%= form.submit "Add note", class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Note entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.user.username %></td>
        <td><%= note.note_entry %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p>
  <strong>Author:</strong>
  <%= @note.user.username %>
</p>

<p>
  <strong>Note entry:</strong>
  <%= @note.note_entry %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/pirates/index.html.erb
<div class="panel-group">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h2 class="panel-title">
        All Users</h2>
    </div>
    <div class="panel-body">
      <table>
        <thead>
          <tr>
            <th>Username</th>
            <th>User email</th>
            <th colspan="1"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.username %></td>
              <td><%= user.email %></td>
              <td><%= link_to 'Show', pirate_path(user), class: "btn btn-success btn-xs" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/pirates/show.html.erb
<div class="panel-group">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h2 class="panel-title">
        User: <%= @user.username %>
      </h2>
    </div>
    <div class="panel-body">
      <p>
        <strong>User email:</strong>
        <%= @user.email %>
      </p>
    </div>
    <div class="panel-footer">
      <%= link_to 'Delete User Account', pirate_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>Title:</h4>
      <div class="form-group">
        <b><%= form.text_field :title, placeholder: "Story Title", class: "form-control" %></b>
      </div>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <%= form.text_area :body, placeholder: "What's the story...", class: "form-control", rows: "17" %>
      </div>
    </div>
    <div class="panel-footer">
      <div class="actions">
        <%= form.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h3 style="color:white;">Editing Story</h3>
<div class="row">
  <div class="col-md-8">
    <%= render 'form', story: @story %>
  </div>
  <div class="col-md-4"><br>
    <div class="panel panel-info">
      <div class="panel-heading">
        <strong>Notes:</strong>
      </div>
      <div class="panel-body">
        <ul>
          <% @story.notes.each do |note| %>
            <div class="row">
              <li>
                <div class="col-md-12">
                  <%= note.note_entry %>
                </div>
              </li>
            </div>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', @story, class: "btn btn-success btn-sm" %>

app/views/stories/index.html.erb
<div class="panel-group">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h2 class="panel-title">
        Stories on <%= current_user.username %>'s bookshelf:
      </h2>
    </div>
    <div class="panel-body">
      <ul>
        <% @stories.each do |story| %>
          <% if current_user.id == story.user.id %>
            <div class="row">
              <li>
                <div class="col-md-4"><b><%= link_to story.title, story %></b></div>
                <div class="col-md-3"><b>Started:</b> <%= story.created_at.strftime('%b %d, %Y %l:%M%P') %></div>
                <div class="col-md-3"><b>Last Edit:</b> <%= story.updated_at.strftime('%b %d, %Y %l:%M%P') %></div>
                <div class="col-md-2">
                  <%= link_to 'Edit', edit_story_path(story), class: "btn btn-success btn-xs" %>
                  <%= link_to 'Delete', story, class: "btn btn-danger btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              </li>
            </div>
          <% end %>        
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/stories/new.html.erb
<h1>New Story</h1>
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <%= render 'form', story: @story %>
  </div>
</div>
<%= link_to 'Back', stories_path, class: "btn btn-success btn-sm" %>

app/views/stories/show.html.erb
<div class="row">
	<div class="col-md-8">
		<div class="panel panel-primary">
			<div class="panel-heading">
        <div class="row">
          <div class="col-md-6"><b>Title:</b><br> <em>"<%= @story.title %>"</em></div>
          <div class="col-md-3"><b>Started:</b><br> <%= @story.created_at.strftime('%b %d, %Y %l:%M%P') %></div>
          <div class="col-md-3"><b>Last Edit:</b><br> <%= @story.updated_at.strftime('%b %d, %Y %l:%M%P') %></div>
        </div>
			</div>
			<div class="panel-body" style="height:28em; overflow-y:scroll;">
				<%= simple_format(@story.body.html_safe) %>
			</div>
			<div class="panel-footer">
				<%= link_to 'Edit Story', edit_story_path(@story), class: "btn btn-success btn-sm" %>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-info">
			<div class="panel-heading">
				<strong>Notes:</strong>
			</div>
			<div class="panel-body">
				<ul>
					<%= render 'notes/form', note: @note %>
					<% @story.notes.each do |note| %>
						<div class="row">
							<li>
								<div class="col-md-8">
									<%= note.note_entry %>
								</div>
					    	<div class="col-md-4">
						    	<%= link_to 'Delete note', note, class: "btn btn-danger btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %>
						    </div>
						  </li>
						</div>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
</div>